import { defineConfig } from "vite";

// The Ferrite DB engine is delivered as a hand-built WASM module (generated by
// `wasm-bindgen --target web` into src/pkg). The Web Worker that drives it is
// emitted as an ES module so it can `import` the generated ESM glue directly.
export default defineConfig({
  build: {
    target: "esnext",
    outDir: "dist",
    sourcemap: true,
    assetsInlineLimit: 0,
  },
  worker: {
    format: "es",
  },
  // .wasm referenced through `new URL(..., import.meta.url)` is emitted as an
  // asset automatically; this keeps it explicit.
  assetsInclude: ["**/*.wasm"],
});
